// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfdbfienscwfdthlmqkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mZGJmaWVuc2N3ZmR0aGxtcWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMjAyNDMsImV4cCI6MjA3Mzc5NjI0M30.WwHjq1zLJy6gXNbLJo6c0vcWeYCTVuUuS4yh9rX7w7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'X-Client-Info': 'smart-wanderer-app'
    }
  }
});
